server.port=${PORT:8107}

spring.datasource.url=jdbc:postgresql://ep-long-frost-aqsui38i-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&connect_timeout=10
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sv8eQTWFZh3n
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true